version: '3'
services:
  server:
    build: server/.
    ports:
      - 2000:2222
  front:
    build:
      context: ./front
      dockerfile: front.dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./front:/var/www/front
  jsonserver:
    build:
      context: ./front
      dockerfile: jsonserver.dockerfile
    ports:
      - 3333:3333
  db:
    image: 'postgres'
    environment:
      POSTGRES_DB: rede_abrigo
      POSTGRES_USER: abrigando
      POSTGRES_PASSWORD: osdesabrigados
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db-data:
