version: '3'
services:
  server:
    build: server/.
    ports:
      - 2000:2222
  front:
    build: front/.
    ports:
      - 3000:3000
  db:
    image: 'postgres'
    environment:
      POSTGRES_DB: rede_abrigo
      POSTGRES_USER: abrigando
      POSTGRES_PASSWORD: osdesabrigados
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db-data:
