name: CI
on: [push]
jobs:
  production:
    if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.PRODUCTION_PROJECT_PATH }}
            git checkout master
            git pull
            docker-compose build
            docker-compose down
            docker-compose up -d
  development:
    if: github.ref == 'refs/heads/develop'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.DEVELOPMENT_PROJECT_PATH }}
            git checkout develop
            git pull
            docker-compose build
            docker-compose down
            docker-compose up -d