name: CI
on: [push]
jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git clone https://github.com/andersonlzcosta/torisjs .
            docker-compose build
            docker-compose down
            docker-compose up